esphome:
  name: mmwave-kit
  friendly_name: mmwave-kit

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:
  hardware_uart: UART0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "6xoutGmrzEbLtIedlxSuWzf729L/s7a1FinK3VIpZ6g="

ota:
  password: "74c0d633b5bf52584c883e17bf612bb1"

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mmwave-kit"
    password: "seeedstudio"

captive_portal:

packages:
  remote_package:
    url: https://github.com/limengdu/MR24HPC1_HomeAssistant/
    ref: mmwave-kit
    files: [packages/mr24hpc1_mmwave_kit.yaml]
    refresh: 1d